CREATE TABLE PBS.STATE_SAVING_CUSTOMER (
    object_id NUMBER(12) NOT NULL,
    timestamp DATE NOT NULL,
    scd_db_flag VARCHAR2(1) NOT NULL,
    validation_date DATE NOT NULL,
    source_object_id NUMBER(12) NOT NULL,
    source_system VARCHAR2(5) NOT NULL,
    status VARCHAR2(16) NOT NULL,
    pps_number VARCHAR2(20) NOT NULL,
    date_of_birth DATE,
    surname VARCHAR2(30) NOT NULL,
    first_name VARCHAR2(30) NOT NULL,
    address_line_1 VARCHAR2(32) NOT NULL,
    address_line_2 VARCHAR2(32),
    city VARCHAR2(32) NOT NULL,
    county VARCHAR2(35),
    country VARCHAR2(50),
    postcode VARCHAR2(10),
    email_address VARCHAR2(50),
    phone_number VARCHAR2(25),
    email_consent VARCHAR2(1),
    phone_consent VARCHAR2(1),
    multiple_sources VARCHAR2(1),
    middle_name VARCHAR2(30),
    title VARCHAR2(6),
    CONSTRAINT pk_state_saving_customer PRIMARY KEY (object_id)
);